# Warnaza — Kitty Terminal Colors
# Mode: dark
# Wallpaper: /home/diaz/Pictures/Wallpapers/4wiw6vd7m2kg1.png

# Backgrounds
background            #181c18
selection_background  #1c3030

# Foregrounds
foreground            #f8c084
selection_foreground  #ece4d4

# Cursor
cursor                #687460
cursor_text_color     #181c18

# URL
url_color             #d08c58

# Terminal 16 colors
# Black — darkest dark, bright = sedikit lebih terang
color0   #181c18
color8   #1c3030

# Red — mid bawah, bright lebih terang
color1   #3c5854
color9   #506054

# Green — mid tengah
color2   #884c38
color10  #606858

# Yellow — mid atas
color3   #a86040
color11  #d89058

# Blue — mid bawah sisi lain
color4   #784030
color12  #884c38

# Magenta — mid atas
color5   #d08c58
color13  #b0a074

# Cyan — dark atas / mid bawah
color6   #304844
color14  #385450

# White — light, bright = paling terang
color7   #f8bc80
color15  #ece4d4
