# ~/.config/kitty/kitty.conf

include ~/.config/kitty/colors.conf

# Window
window_padding_width 10

# Opacity
background_opacity 0.90

# Font
font_family JetBrains Mono
font_size 9

# Cursor
cursor_shape block
