[General]
operation_mode = full
mode = auto
brightness_threshold = 124

[Extraction]
bin_size = 4
delta_min = 9.0

[Paths]
templates_dir = templates
cache_dir = ~/.cache/warnaza
config_dir = ~/.config/warnaza

[Features]
generate_preview = true
set_wallpaper = false
apply_xresources = false
run_post_script = true
create_symlink = true
deploy_configs = true

[Hooks]
scripts_dir = ~/.config/warnaza/hooks

[Hook.Scripts]
enabled = true
scripts = awww.sh, hyprland.sh, gtk-3.0.sh, gtk-3.20.sh, gtkrc.sh, kitty.sh, nvim.sh, kdeglobals.sh, kde-colors.sh, gtk-4.0.sh

[PostScript]
script_path = warnaza-post.sh

